### ISSUE TITLE
No "models" folder present after installation

### ISSUE THREAD

**Issue by robdjeff** [ellawang44/Breidablik#7]
Hello again. I am making progress, but:

I installed breidablik 1.3.0 using the pip installer. It puts the packages into a folder called
.../site-packages/breidablik

which contains subfolders
analysis
Balder
interpolate

However, there isn't a subfolder called "models" and when I run my code I get the error message (from scalar.py) because it is looking for a file in a subfolder called "models" (see below).

Should the installation have created a models folder? Or is it created when the code is run?

Traceback (most recent call last):

  File ~\anaconda3\envs\work\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\cygwin64\home\robdj\tex\gesliscatter\nltegrid.py:15
    mymodel = Nlte()

  File ~\anaconda3\envs\work\lib\site-packages\breidablik\interpolate\nlte.py:34 in __init__
    scalar.load(scalar_path)

  File ~\anaconda3\envs\work\lib\site-packages\breidablik\interpolate\scalar.py:124 in load
    raise FileNotFoundError('Attempted to load a scalar not found, path given: {}'.format(path))

FileNotFoundError: Attempted to load a scalar not found, path given: C:\Users\robdj\anaconda3\envs\work\lib\site-packages\breidablik\models\nlte\scalar.npy

**Comment by ellawang44** [comment]
Apologies, that's my fault. I forgot to include the models in the pypi build. 

This is now fixed in `v1.4.0`, update your code through pip and it should work. 

I've pulled `v1.3.0` since it requires a manual install of the models.

**Comment by robdjeff** [comment]
Resolved! Thanks very much. Now to debug my own code...
